const stages=['Nowy lead','Do kontaktu','Kontakt wykonany','Kwalifikacja','Oferta','Follow-up','Wygrany','Przegrany'];
const seed=[
{id:1,company:'NovaTech sp. z o.o.',contact:'Anna Kowalska',email:'anna@novatech.pl',phone:'500 100 200',source:'Google Ads',mrr:1800,grade:'A',stage:'Oferta',followup:'2026-10-01',note:'Pełna księgowość + 12 pracowników'},
{id:2,company:'Studio Forma',contact:'Michał Nowak',email:'m.nowak@example.pl',phone:'501 222 333',source:'Polecenie',mrr:950,grade:'A',stage:'Follow-up',followup:'2026-09-29',note:'JDG + VAT + 2 pracowników'},
{id:3,company:'Baltic Commerce',contact:'Katarzyna Lis',email:'k.lis@example.pl',phone:'502 321 444',source:'SEO',mrr:2400,grade:'B',stage:'Kwalifikacja',followup:'2026-10-03',note:'Sp. z o.o., e-commerce'},
{id:4,company:'Green Office',contact:'Piotr Wrona',email:'piotr@example.pl',phone:'503 555 600',source:'Partner',mrr:1200,grade:'B',stage:'Kontakt wykonany',followup:'2026-10-02',note:'Zmiana biura od listopada'},
{id:5,company:'Kancelaria LexPoint',contact:'Joanna Maj',email:'joanna@example.pl',phone:'504 111 789',source:'Polecenie',mrr:3200,grade:'A',stage:'Wygrany',followup:'2026-10-05',note:'Pełna księgowość + kadry'},
{id:6,company:'CraftLab',contact:'Tomasz Zając',email:'tomasz@example.pl',phone:'505 888 910',source:'Social media',mrr:700,grade:'C',stage:'Przegrany',followup:'',note:'Cena ponad budżet'},
{id:7,company:'Serwis MotoPro',contact:'Paweł Kopeć',email:'pawel@example.pl',phone:'506 333 222',source:'Formularz WWW',mrr:1350,grade:'B',stage:'Nowy lead',followup:'2026-10-01',note:'KPiR + VAT'},
{id:8,company:'Medica Plus',contact:'Ewa Mazur',email:'ewa@example.pl',phone:'507 888 111',source:'SEO',mrr:2100,grade:'A',stage:'Do kontaktu',followup:'2026-09-30',note:'Sp. z o.o. + kadry'}];
let leads=JSON.parse(localStorage.getItem('brcrm.leads')||'null')||seed;
const moduleSeed={
users:[['Anna Kowalska','Administrator'],['Michał Nowak','Sprzedaż'],['Joanna Maj','Księgowość']],
history:[['Zmiana etapu','NovaTech → Oferta'],['Dodano lead','Medica Plus'],['Zmieniono MRR','Studio Forma → 950 zł']],
timeline:[['09:10','Telefon do Studio Forma'],['10:30','Oferta dla NovaTech'],['14:00','Follow-up Medica Plus']],
board:[['Cel miesiąca','10 nowych klientów'],['Priorytet','Oddzwonić do leadów A'],['Informacja','Nowy cennik od października']],
reminders:[['Dziś','Follow-up Studio Forma'],['Jutro','Telefon Medica Plus'],['03.10','Powrót do Baltic Commerce']],
files:[['Cennik_2026.pdf','PDF'],['Oferta_wzor.docx','DOCX'],['Onboarding_checklista.xlsx','XLSX']],
emails:[['Oferta dla NovaTech','Wysłana'],['Follow-up Studio Forma','Do wysłania'],['Powitanie Kancelaria LexPoint','Wysłana']],
snippets:[['Follow-up po ofercie','Dzień dobry, wracam do przesłanej oferty...'],['Pierwszy kontakt','Dzień dobry, dziękujemy za kontakt...']],
clients:[['Kancelaria LexPoint','3 200 zł MRR'],['Nova Retail','1 650 zł MRR'],['Arch Studio','980 zł MRR']],
groups:[['VIP','8 klientów'],['E-commerce','14 klientów'],['JDG','31 klientów']],
contacts:[['Joanna Maj','Kancelaria LexPoint'],['Anna Kowalska','NovaTech'],['Ewa Mazur','Medica Plus']],
notes:[['NovaTech','Decyzja po spotkaniu zarządu'],['Studio Forma','Wrażliwi na cenę'],['Baltic Commerce','Potrzebują kadr']],
sequences:[['Nowy lead — 5 dni','3 wiadomości'],['Po wysłaniu oferty','2 wiadomości']],
automations:[['Nowy lead → przypomnienie','Aktywna'],['Oferta bez odpowiedzi 3 dni','Aktywna'],['Wygrany → onboarding','Aktywna']],
offers:[['OF/09/2026/18','NovaTech • 1 800 zł/m-c'],['OF/09/2026/19','Studio Forma • 950 zł/m-c']],
orders:[['ZAM/09/26/04','Kancelaria LexPoint • aktywne'],['ZAM/09/26/05','Nova Retail • aktywne']],
invoices:[['FV/09/2026/122','Kancelaria LexPoint • 3 200 zł'],['FV/09/2026/123','Nova Retail • 1 650 zł']],
proformas:[['PF/09/2026/14','Baltic Commerce • 2 400 zł']],
payments:[['FV/09/2026/122','Opłacona'],['FV/09/2026/123','Oczekuje']],
products:[['Księgowość pełna','1 200 zł'],['Kadry i płace / osoba','90 zł'],['KPiR','450 zł']]
};
let modules=JSON.parse(localStorage.getItem('brcrm.modules')||'null')||moduleSeed;
let view='pipeline';
const app=document.querySelector('#app'),title=document.querySelector('#viewTitle'),subtitle=document.querySelector('#subtitle'),crumb=document.querySelector('#crumb'),addLeadBtn=document.querySelector('#addLead');
const labels={dashboard:['Pulpit','Najważniejsze wskaźniki sprzedaży.'],users:['Użytkownicy','Zespół i role w CRM.'],history:['Historia zmian','Rejestr najważniejszych zmian w systemie.'],timeline:['Oś czasu','Aktywności i zdarzenia sprzedażowe.'],board:['Tablica informacyjna','Wewnętrzne komunikaty i priorytety.'],reminders:['Przypomnienia','Zadania i terminy wymagające działania.'],files:['Pliki','Dokumenty używane w sprzedaży i onboardingu.'],emails:['Wiadomości e-mail','Robocza skrzynka i status korespondencji.'],snippets:['Fragmenty tekstu','Gotowe treści do szybkiego użycia.'],clients:['Klienci','Aktywni klienci biura rachunkowego.'],leads:['Leady / Potencjalni klienci','Pełna lista kontaktów sprzedażowych.'],groups:['Grupy klientów','Segmentacja klientów.'],contacts:['Osoby kontaktowe','Kontakty powiązane z firmami.'],notes:['Notatki','Notatki handlowe i operacyjne.'],sequences:['Sekwencje e-mail','Zaplanowane serie wiadomości.'],automations:['Automatyzacje','Reguły automatyzujące proces sprzedaży.'],pipeline:['Szanse sprzedaży','Zarządzaj leadami i przesuwaj je przez kolejne etapy sprzedaży.'],offers:['Oferty','Wysłane i przygotowywane oferty.'],orders:['Zamówienia','Aktywowane usługi i zamówienia.'],invoices:['Faktury','Rejestr faktur sprzedażowych.'],proformas:['Faktury pro forma','Dokumenty pro forma.'],payments:['Płatności','Status rozliczeń klientów.'],products:['Produkty / Magazyn','Cennik usług i produktów.']};
const money=n=>new Intl.NumberFormat('pl-PL',{style:'currency',currency:'PLN',maximumFractionDigits:0}).format(n||0);
const save=()=>localStorage.setItem('brcrm.leads',JSON.stringify(leads));
const saveModules=()=>localStorage.setItem('brcrm.modules',JSON.stringify(modules));
const overdue=d=>d&&new Date(d)<new Date(new Date().toISOString().slice(0,10));
function render(){document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===view));const [t,s]=labels[view]||[view,''];title.textContent=t;subtitle.textContent=s;crumb.textContent=(['dashboard','users','history','timeline','board','reminders','files','emails','snippets'].includes(view)?'OGÓLNE / ':'CRM / ')+t;addLeadBtn.style.display=view==='pipeline'||view==='leads'?'inline-block':'none';app.innerHTML='';if(view==='dashboard')dashboard();else if(view==='pipeline')pipeline();else if(view==='leads')leadTable();else genericModule(view)}
function dashboard(){const open=leads.filter(l=>!['Wygrany','Przegrany'].includes(l.stage)),won=leads.filter(l=>l.stage==='Wygrany'),mrr=won.reduce((a,l)=>a+l.mrr,0),conv=leads.length?Math.round(won.length/leads.length*100):0;app.innerHTML=`<div class="kpis"><div class="card kpi"><div class="label">Aktywne leady</div><div class="value">${open.length}</div><div class="delta">w pipeline</div></div><div class="card kpi"><div class="label">Nowy MRR</div><div class="value">${money(mrr)}</div><div class="delta">wygrane szanse</div></div><div class="card kpi"><div class="label">Konwersja lead → klient</div><div class="value">${conv}%</div><div class="delta">${won.length} wygranych</div></div><div class="card kpi"><div class="label">Wartość pipeline</div><div class="value">${money(open.reduce((a,l)=>a+l.mrr,0))}</div><div class="delta">potencjalny MRR</div></div></div><div class="dashboard-grid"><div class="card"><h3 class="section-title">Lejek sprzedażowy</h3>${stages.slice(0,7).map(s=>{let c=leads.filter(l=>l.stage===s).length,p=leads.length?Math.round(c/leads.length*100):0;return `<div class="funnel-row"><div>${s}<div class="bar"><i style="width:${Math.max(p,4)}%"></i></div></div><b>${c}</b></div>`}).join('')}</div><div class="card"><h3 class="section-title">Najbliższe przypomnienia</h3>${modules.reminders.map(r=>`<div class="source-row"><span>${r[0]}</span><b>${r[1]}</b></div>`).join('')}</div></div>`}
function pipeline(){app.innerHTML=`<div class="board-tools"><input id="boardSearch" placeholder="Szukaj szansy..."><select id="boardSource"><option value="">Wszystkie źródła</option>${[...new Set(leads.map(l=>l.source))].map(s=>`<option>${s}</option>`).join('')}</select><select id="boardGrade"><option value="">Każdy segment</option><option>A</option><option>B</option><option>C</option></select></div><div id="pipelineBoard" class="pipeline"></div>`;const draw=()=>{const q=document.querySelector('#boardSearch').value.toLowerCase(),src=document.querySelector('#boardSource').value,gr=document.querySelector('#boardGrade').value,filtered=leads.filter(l=>(!src||l.source===src)&&(!gr||l.grade===gr)&&(`${l.company} ${l.contact}`.toLowerCase().includes(q)));document.querySelector('#pipelineBoard').innerHTML=stages.map(s=>{const ls=filtered.filter(l=>l.stage===s),total=ls.reduce((a,l)=>a+l.mrr,0);return `<div class="column"><div class="column-head"><div>${s}<span class="column-total">${money(total)} MRR</span></div><span class="count">${ls.length}</span></div><div class="column-body">${ls.map(card).join('')||'<div class="empty">Brak szans</div>'}</div></div>`}).join('');document.querySelectorAll('.lead-card').forEach(el=>el.onclick=()=>advance(Number(el.dataset.id)))};['#boardSearch','#boardSource','#boardGrade'].forEach(sel=>document.querySelector(sel).addEventListener('input',draw));draw()}
function card(l){return `<div class="lead-card" data-id="${l.id}"><span class="more">⋮</span><h4>${l.company}</h4><p>${l.contact}</p><div class="lead-price">${money(l.mrr)}</div><div class="lead-meta"><span>${l.followup||'brak terminu'} ${overdue(l.followup)?'<span class="overdue-badge">po terminie</span>':''}</span><span class="grade-dot grade-${l.grade.toLowerCase()}">${l.grade}</span></div></div>`}
function advance(id){const l=leads.find(x=>x.id===id),i=stages.indexOf(l.stage);if(i<stages.length-1)l.stage=stages[i+1];save();render()}
function leadTable(){app.innerHTML=`<div class="toolbar"><input id="q" placeholder="Szukaj firmy lub kontaktu…"><select id="stageFilter"><option value="">Wszystkie etapy</option>${stages.map(s=>`<option>${s}</option>`).join('')}</select></div><div class="table-wrap"><table><thead><tr><th>Firma</th><th>Kontakt</th><th>Źródło</th><th>Etap</th><th>Segment</th><th>MRR</th><th>Follow-up</th></tr></thead><tbody id="rows"></tbody></table></div>`;const draw=()=>{let q=document.querySelector('#q').value.toLowerCase(),sf=document.querySelector('#stageFilter').value;document.querySelector('#rows').innerHTML=leads.filter(l=>(!sf||l.stage===sf)&&(`${l.company} ${l.contact}`.toLowerCase().includes(q))).map(l=>`<tr><td><b>${l.company}</b><br><small>${l.note||''}</small></td><td>${l.contact}<br><small>${l.email||''}</small></td><td>${l.source}</td><td>${l.stage}</td><td><span class="chip ${l.grade.toLowerCase()}">${l.grade}</span></td><td>${money(l.mrr)}</td><td class="${overdue(l.followup)?'overdue':'ok'}">${l.followup||'—'}</td></tr>`).join('')};document.querySelector('#q').oninput=draw;document.querySelector('#stageFilter').onchange=draw;draw()}
function genericModule(key){const rows=modules[key]||[];app.innerHTML=`<div class="module-actions"><button class="secondary" id="addModule">+ Dodaj</button><input id="moduleSearch" placeholder="Szukaj..."></div><div class="module-grid" id="moduleGrid"></div>`;const draw=()=>{const q=document.querySelector('#moduleSearch').value.toLowerCase();document.querySelector('#moduleGrid').innerHTML=rows.filter(r=>r.join(' ').toLowerCase().includes(q)).map((r,i)=>`<div class="module-card"><div class="module-icon">${i+1}</div><div><b>${r[0]}</b><span>${r[1]||''}</span></div><button class="delete-item" data-i="${i}">×</button></div>`).join('')||'<div class="empty card">Brak danych</div>';document.querySelectorAll('.delete-item').forEach(b=>b.onclick=()=>{rows.splice(Number(b.dataset.i),1);saveModules();draw()})};document.querySelector('#moduleSearch').oninput=draw;document.querySelector('#addModule').onclick=()=>{const a=prompt('Nazwa / tytuł:');if(!a)return;const b=prompt('Opis / status:')||'';rows.unshift([a,b]);modules[key]=rows;saveModules();draw()};draw()}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{view=b.dataset.view;render()});
const modal=document.querySelector('#modal');addLeadBtn.onclick=()=>modal.classList.remove('hidden');document.querySelector('#quickAdd').onclick=()=>modal.classList.remove('hidden');document.querySelector('#closeModal').onclick=()=>modal.classList.add('hidden');document.querySelector('#leadForm').onsubmit=e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target));leads.unshift({id:Date.now(),company:d.company,contact:d.contact,email:d.email,phone:d.phone,source:d.source,mrr:Number(d.mrr)||0,grade:d.grade,stage:'Nowy lead',followup:d.followup,note:d.note});save();modules.history.unshift(['Dodano lead',d.company]);saveModules();e.target.reset();modal.classList.add('hidden');render()};
document.querySelector('#globalSearch').oninput=e=>{const q=e.target.value.toLowerCase();if(!q)return;const hit=leads.find(l=>`${l.company} ${l.contact} ${l.email}`.toLowerCase().includes(q));if(hit){view='leads';render();const inp=document.querySelector('#q');if(inp){inp.value=e.target.value;inp.dispatchEvent(new Event('input'))}}};
render();