const stages=['Nowy lead','Do kontaktu','Kontakt wykonany','Kwalifikacja','Oferta','Follow-up','Wygrany','Przegrany'];
const seed=[
{id:1,company:'NovaTech sp. z o.o.',contact:'Anna Kowalska',email:'anna@novatech.pl',phone:'500 100 200',source:'Google Ads',mrr:1800,grade:'A',stage:'Oferta',followup:'2026-10-01',note:'Pełna księgowość + 12 pracowników'},
{id:2,company:'Studio Forma',contact:'Michał Nowak',email:'m.nowak@example.pl',phone:'501 222 333',source:'Polecenie',mrr:950,grade:'A',stage:'Follow-up',followup:'2026-09-29',note:'JDG + VAT + 2 pracowników'},
{id:3,company:'Baltic Commerce',contact:'Katarzyna Lis',email:'k.lis@example.pl',phone:'502 321 444',source:'SEO',mrr:2400,grade:'B',stage:'Kwalifikacja',followup:'2026-10-03',note:'Sp. z o.o., e-commerce'},
{id:4,company:'Green Office',contact:'Piotr Wrona',email:'piotr@example.pl',phone:'503 555 600',source:'Partner',mrr:1200,grade:'B',stage:'Kontakt wykonany',followup:'2026-10-02',note:'Zmiana biura od listopada'},
{id:5,company:'Kancelaria LexPoint',contact:'Joanna Maj',email:'joanna@example.pl',phone:'504 111 789',source:'Polecenie',mrr:3200,grade:'A',stage:'Wygrany',followup:'2026-10-05',note:'Pełna księgowość + kadry'},
{id:6,company:'CraftLab',contact:'Tomasz Zając',email:'tomasz@example.pl',phone:'505 888 910',source:'Social media',mrr:700,grade:'C',stage:'Przegrany',followup:'',note:'Cena ponad budżet'},
{id:7,company:'Serwis MotoPro',contact:'Paweł Kopeć',email:'pawel@example.pl',phone:'506 333 222',source:'Formularz WWW',mrr:1350,grade:'B',stage:'Nowy lead',followup:'2026-10-01',note:'KPiR + VAT'},
{id:8,company:'Medica Plus',contact:'Ewa Mazur',email:'ewa@example.pl',phone:'507 888 111',source:'SEO',mrr:2100,grade:'A',stage:'Do kontaktu',followup:'2026-09-30',note:'Sp. z o.o. + kadry'}];
let leads=JSON.parse(localStorage.getItem('brcrm.leads')||'null')||seed;let view='pipeline';
const app=document.querySelector('#app'),title=document.querySelector('#viewTitle'),subtitle=document.querySelector('#subtitle');
const money=n=>new Intl.NumberFormat('pl-PL',{style:'currency',currency:'PLN',maximumFractionDigits:0}).format(n||0);
const save=()=>localStorage.setItem('brcrm.leads',JSON.stringify(leads));
const overdue=d=>d&&new Date(d)<new Date(new Date().toISOString().slice(0,10));
function render(){document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===view));const names={dashboard:['Pulpit','Najważniejsze wskaźniki sprzedaży.'],pipeline:['Szanse sprzedaży','Zarządzaj leadami i przesuwaj je przez kolejne etapy sprzedaży.'],leads:['Leady / potencjalni klienci','Pełna lista kontaktów sprzedażowych.'],reports:['Raporty','Konwersje, źródła i wartość sprzedaży.'],settings:['Ustawienia','Konfiguracja procesu CRM.']};[title.textContent,subtitle.textContent]=names[view];app.innerHTML='';if(view==='dashboard')dashboard();if(view==='pipeline')pipeline();if(view==='leads')leadTable();if(view==='reports')reports();if(view==='settings')settings()}
function dashboard(){const open=leads.filter(l=>!['Wygrany','Przegrany'].includes(l.stage)),won=leads.filter(l=>l.stage==='Wygrany'),mrr=won.reduce((a,l)=>a+l.mrr,0),conv=leads.length?Math.round(won.length/leads.length*100):0;app.innerHTML=`<div class="kpis"><div class="card kpi"><div class="label">Aktywne leady</div><div class="value">${open.length}</div><div class="delta">w pipeline</div></div><div class="card kpi"><div class="label">Nowy MRR</div><div class="value">${money(mrr)}</div><div class="delta">wygrane szanse</div></div><div class="card kpi"><div class="label">Konwersja lead → klient</div><div class="value">${conv}%</div><div class="delta">${won.length} wygranych</div></div><div class="card kpi"><div class="label">Wartość pipeline</div><div class="value">${money(open.reduce((a,l)=>a+l.mrr,0))}</div><div class="delta">potencjalny MRR</div></div></div><div class="dashboard-grid"><div class="card"><h3 class="section-title">Lejek sprzedażowy</h3>${stages.slice(0,7).map(s=>{let c=leads.filter(l=>l.stage===s).length,p=leads.length?Math.round(c/leads.length*100):0;return `<div class="funnel-row"><div>${s}<div class="bar"><i style="width:${Math.max(p,4)}%"></i></div></div><b>${c}</b></div>`}).join('')}</div><div class="card"><h3 class="section-title">Źródła leadów</h3>${sourceRows()}</div></div>`}
function sourceRows(){const map={};leads.forEach(l=>(map[l.source]??=[]).push(l));return Object.entries(map).sort((a,b)=>b[1].length-a[1].length).map(([s,ls])=>`<div class="source-row"><span>${s}</span><b>${ls.length} • ${money(ls.reduce((a,l)=>a+l.mrr,0))}</b></div>`).join('')}
function pipeline(){app.innerHTML=`<div class="board-tools"><input id="boardSearch" placeholder="Szukaj szansy..."><select id="boardSource"><option value="">Wszystkie źródła</option>${[...new Set(leads.map(l=>l.source))].map(s=>`<option>${s}</option>`).join('')}</select><select id="boardGrade"><option value="">Każdy segment</option><option>A</option><option>B</option><option>C</option></select></div><div id="board" class="pipeline"></div>`;const draw=()=>{const q=document.querySelector('#boardSearch').value.toLowerCase(),src=document.querySelector('#boardSource').value,gr=document.querySelector('#boardGrade').value,filtered=leads.filter(l=>(!src||l.source===src)&&(!gr||l.grade===gr)&&(`${l.company} ${l.contact}`.toLowerCase().includes(q)));document.querySelector('#board').innerHTML=stages.map(s=>{const ls=filtered.filter(l=>l.stage===s),total=ls.reduce((a,l)=>a+l.mrr,0);return `<div class="column"><div class="column-head"><div>${s}<span class="column-total">${money(total)} MRR</span></div><span class="count">${ls.length}</span></div><div class="column-body">${ls.map(card).join('')||'<div class="empty">Brak szans</div>'}</div></div>`}).join('');document.querySelectorAll('.lead-card').forEach(el=>el.onclick=()=>advance(Number(el.dataset.id)))};['#boardSearch','#boardSource','#boardGrade'].forEach(sel=>document.querySelector(sel).addEventListener('input',draw));draw()}
function card(l){return `<div class="lead-card" data-id="${l.id}" title="Kliknij, aby przesunąć do kolejnego etapu"><span class="more">⋮</span><h4>${l.company}</h4><p>${l.contact}</p><div class="lead-price">${money(l.mrr)}</div><div class="lead-meta"><span>${l.followup||'brak terminu'} ${overdue(l.followup)?'<span class="overdue-badge">po terminie</span>':''}</span><span class="grade-dot grade-${l.grade.toLowerCase()}">${l.grade}</span></div></div>`}
function advance(id){const l=leads.find(x=>x.id===id),i=stages.indexOf(l.stage);if(i<stages.length-1)l.stage=stages[i+1];save();render()}
function leadTable(){app.innerHTML=`<div class="toolbar"><input id="q" placeholder="Szukaj firmy lub kontaktu…"><select id="stageFilter"><option value="">Wszystkie etapy</option>${stages.map(s=>`<option>${s}</option>`).join('')}</select></div><div class="table-wrap"><table><thead><tr><th>Firma</th><th>Kontakt</th><th>Źródło</th><th>Etap</th><th>Segment</th><th>MRR</th><th>Follow-up</th></tr></thead><tbody id="rows"></tbody></table></div>`;const draw=()=>{let q=document.querySelector('#q').value.toLowerCase(),sf=document.querySelector('#stageFilter').value;document.querySelector('#rows').innerHTML=leads.filter(l=>(!sf||l.stage===sf)&&(`${l.company} ${l.contact}`.toLowerCase().includes(q))).map(l=>`<tr><td><b>${l.company}</b><br><small>${l.note||''}</small></td><td>${l.contact}<br><small>${l.email||''}</small></td><td>${l.source}</td><td>${l.stage}</td><td><span class="chip ${l.grade.toLowerCase()}">${l.grade}</span></td><td>${money(l.mrr)}</td><td class="${overdue(l.followup)?'overdue':'ok'}">${l.followup||'—'}</td></tr>`).join('')};document.querySelector('#q').oninput=draw;document.querySelector('#stageFilter').onchange=draw;draw()}
function reports(){const won=leads.filter(l=>l.stage==='Wygrany'),lost=leads.filter(l=>l.stage==='Przegrany'),offered=leads.filter(l=>['Oferta','Follow-up','Wygrany','Przegrany'].includes(l.stage));const offerConv=offered.length?Math.round(won.length/offered.length*100):0;app.innerHTML=`<div class="report-grid"><div class="card"><h3 class="section-title">Konwersje</h3><div class="metric-list"><div class="metric"><span>Lead → klient</span><b>${leads.length?Math.round(won.length/leads.length*100):0}%</b></div><div class="metric"><span>Oferta → klient</span><b>${offerConv}%</b></div><div class="metric"><span>Wygrane</span><b>${won.length}</b></div><div class="metric"><span>Przegrane</span><b>${lost.length}</b></div></div></div><div class="card"><h3 class="section-title">Finanse</h3><div class="metric-list"><div class="metric"><span>Wygrany MRR</span><b>${money(won.reduce((a,l)=>a+l.mrr,0))}</b></div><div class="metric"><span>ARR</span><b>${money(won.reduce((a,l)=>a+l.mrr*12,0))}</b></div><div class="metric"><span>Śr. MRR klienta</span><b>${money(won.length?won.reduce((a,l)=>a+l.mrr,0)/won.length:0)}</b></div></div></div></div>`}
function settings(){app.innerHTML=`<div class="card"><h3 class="section-title">Etapy procesu</h3><div>${stages.map(s=>`<span class="chip">${s}</span> `).join('')}</div><p style="color:var(--muted);margin-top:18px;font-size:12px">W MVP ustawienia są stałe.</p><button id="reset" class="primary">Przywróć dane demo</button></div>`;document.querySelector('#reset').onclick=()=>{leads=structuredClone(seed);save();render()}}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{view=b.dataset.view;render()});const modal=document.querySelector('#modal');document.querySelector('#addLead').onclick=()=>modal.classList.remove('hidden');document.querySelector('#closeModal').onclick=()=>modal.classList.add('hidden');document.querySelector('#leadForm').onsubmit=e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target));leads.unshift({id:Date.now(),company:d.company,contact:d.contact,email:d.email,phone:d.phone,source:d.source,mrr:Number(d.mrr)||0,grade:d.grade,stage:'Nowy lead',followup:d.followup,note:d.note});save();e.target.reset();modal.classList.add('hidden');render()};render();